spring:
  application:
    name: games-service-library
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  sql:
    init:
      dataLocations: classpath:/games-service-library.sql
  jpa:
    deferDatasourceInitialization: true
    hibernate:
      ddlAuto: create-drop

server:
  port: 8091

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
