spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: games-service-route
          uri: lb://games-service
          predicates:
            - Path=/games/**
        - id: games-service-library-route
          uri: lb://games-service-library
          predicates:
            - Path=/library/**

server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
