spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        registration:
          github:
            cliend-id: 67fd42feca05c91f2a53
            client-secret: c56f10067e276ce0b7d33ed9cbd0e3e4fe5845ec
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: movie-service-route
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: catalog-service-route
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**

server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
