spring:
  application:
    name: serie-service
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  data:
    mongodb:
      host: localhost
      port: 27017
      database: serie_database
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  mvc:
    log-request-details: true
  zipkin:
    base-url: http:zipkin:9411/
    enabled: true

queue:
  serie:
    name: SerieQueue

message: registro up

server:
  port: 8082

logging:
  level:
    org.springframework.security: DEBUG

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
